server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  packagesToScan: book.store

spring:
  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secretKey: 'book-store'
  tokenLifetimeInMinutes: 90