server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/v1/book/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/api/v1/api-docs/**


springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v1/api-docs/user
      - name: book
        url: /v1/api-docs/book
      - name: order
        url: /v1/api-docs/order

management:
  tracing:
    sampling:
      probability: 1.0